"""Invented hourly series for the Package 5 baselines and backtester.

``build_spec()`` regenerates ``tests/fixtures/synthetic/research/series.v1.json``
exactly (a test checks this), so every count in the committed fixture can be
traced to its seed. ``captures()`` expands one scenario into ordinary
``synthetic-fixture`` capture documents, which the tests load through the real
capture pipeline and rollups. Every record is invented.
"""

from __future__ import annotations

import json
import math
import random
from datetime import UTC, date, datetime, timedelta

SPEC_FORMAT = "eye.synthetic-research-series/1"
FIRST_DAY = date(2026, 3, 1)
DAYS = 22
BLOCK_HOURS = 3
# Mean observed states per UTC hour: quiet nights, a busier day.
PATTERN = [1, 1, 1, 1, 1, 2, 3, 4, 5, 5, 4, 4, 4, 4, 4, 5, 5, 4, 3, 3, 2, 2, 1, 1]
POISSON_SEED = 1
SHUFFLE_SEED = 2
PLANTED = ("2026-03-22", 13, 20)  # day, hour, states added
TARGET_OUTAGE = ("2026-03-22", 6)  # day, block (hours 18-20): a provider timeout
PARTIAL = ("2026-03-18", 3)  # day, block (hours 09-11): provider covered 09-11 only
HISTORY_OUTAGE_BLOCK = 2  # hours 06-08 failed on every day before the last


def _poisson(rng: random.Random, mean: float) -> int:
    limit, k, p = math.exp(-mean), 0, 1.0
    while True:
        p *= rng.random()
        if p < limit:
            return k
        k += 1


def _day(i: int) -> str:
    return (FIRST_DAY + timedelta(days=i)).isoformat()


def build_spec() -> dict:
    rng = random.Random(POISSON_SEED)  # noqa: S311 - a reproducible fixture, not a secret
    null = [[_poisson(rng, m) for m in PATTERN] for _ in range(DAYS)]
    planted = [row[:] for row in null]
    day_index = (date.fromisoformat(PLANTED[0]) - FIRST_DAY).days
    planted[day_index][PLANTED[1]] += PLANTED[2]
    flat = [v for row in null for v in row]
    random.Random(SHUFFLE_SEED).shuffle(flat)  # noqa: S311 - a reproducible fixture
    shuffled = [flat[i * 24 : (i + 1) * 24] for i in range(DAYS)]
    outages = [list(TARGET_OUTAGE)]
    partial = [list(PARTIAL)]
    return {
        "format": SPEC_FORMAT,
        "synthetic": True,
        "note": (
            "Invented hourly counts of observed vessel states for the Package 5 baseline "
            "and backtester controls. Generated by tests/support/synthetic_research.py."
        ),
        "source_id": "synthetic-fixture",
        "layer": "vessel",
        "bbox": [-1.0, -1.0, 1.0, 1.0],
        "first_day": FIRST_DAY.isoformat(),
        "block_hours": BLOCK_HOURS,
        "generator": {
            "pattern": PATTERN,
            "poisson_seed": POISSON_SEED,
            "shuffle_seed": SHUFFLE_SEED,
        },
        "scenarios": {
            "null": {"counts": null, "outages": outages, "partial": partial, "planted": []},
            "planted": {
                "counts": planted,
                "outages": outages,
                "partial": partial,
                "planted": [list(PLANTED)],
            },
            "shuffled": {"counts": shuffled, "outages": outages, "partial": partial, "planted": []},
            "outage": {
                "counts": null,
                "outages": [[_day(i), HISTORY_OUTAGE_BLOCK] for i in range(DAYS - 1)] + outages,
                "partial": partial,
                "planted": [],
            },
        },
        # A backfill delivered after the day's rollups: the timed-out block of
        # the null scenario arrives late, complete.
        "late": {"scenario": "null", "received": "2026-03-24T00:00:00Z", "blocks": outages},
    }


def _iso(moment: datetime) -> str:
    return moment.strftime("%Y-%m-%dT%H:%M:%SZ")


def _doc(
    spec: dict,
    day: str,
    block: int,
    counts: list[int],
    status: str,
    received: str,
    observed_hours: int | None = None,
) -> bytes:
    start = datetime.fromisoformat(day).replace(tzinfo=UTC) + timedelta(hours=block * BLOCK_HOURS)
    end = start + timedelta(hours=BLOCK_HOURS)
    observed_end = end if observed_hours is None else start + timedelta(hours=observed_hours)
    records = []
    if status == "ok":
        for h in range(BLOCK_HOURS):
            hour_start = start + timedelta(hours=h)
            if hour_start >= observed_end:
                break
            for i in range(counts[block * BLOCK_HOURS + h]):
                observed = hour_start + timedelta(seconds=17 + i * 61)
                records.append(
                    {
                        "record_id": f"SYN-RES-{day.replace('-', '')}-{block}{h}-{i:03d}",
                        "observed_time": _iso(observed),
                        "source_published_time": _iso(observed + timedelta(seconds=5)),
                        "lon": round(-0.9 + 0.013 * i, 3),
                        "lat": round(-0.5 + 0.1 * h, 3),
                        "alt_m": None,
                        "confidence": 0.9,
                        "quality_flags": [],
                    }
                )
    doc = {
        "capture_format": "eye.synthetic-capture/2",
        "synthetic": True,
        "source_id": spec["source_id"],
        "adapter_version": "synthetic-adapter/2",
        "note": f"Research fixture {day} block {block} ({status}).",
        "layer": spec["layer"],
        "request": {
            "bbox": spec["bbox"],
            "start": _iso(start),
            "end": _iso(end),
            "expected_interval_s": 600,
        },
        "attempt": {
            "written_by": "EYE capture adapter; finished_at is the EYE receipt time",
            "started_at": received,
            "finished_at": received,
            "provider_status": status,
            "quota_cost": 0,
            "observed_start": _iso(start),
            "observed_end": _iso(observed_end),
        },
        "provider_response": {"records": records},
    }
    return json.dumps(doc, sort_keys=True).encode()


def captures(spec: dict, scenario: str) -> list[bytes]:
    """Every capture of one scenario, in time order: 24 / block_hours per day."""
    sc = spec["scenarios"][scenario]
    outages = {tuple(o) for o in sc["outages"]}
    partial = {tuple(p) for p in sc["partial"]}
    first = date.fromisoformat(spec["first_day"])
    out = []
    for i, counts in enumerate(sc["counts"]):
        day = (first + timedelta(days=i)).isoformat()
        for block in range(24 // spec["block_hours"]):
            end = datetime.fromisoformat(day).replace(tzinfo=UTC) + timedelta(
                hours=(block + 1) * spec["block_hours"]
            )
            received = _iso(end + timedelta(minutes=5))
            if (day, block) in outages:
                out.append(_doc(spec, day, block, counts, "timeout", received))
            elif (day, block) in partial:
                out.append(_doc(spec, day, block, counts, "ok", received, observed_hours=2))
            else:
                out.append(_doc(spec, day, block, counts, "ok", received))
    return out


def late_captures(spec: dict) -> list[bytes]:
    late = spec["late"]
    sc = spec["scenarios"][late["scenario"]]
    first = date.fromisoformat(spec["first_day"])
    out = []
    for day, block in late["blocks"]:
        counts = sc["counts"][(date.fromisoformat(day) - first).days]
        out.append(_doc(spec, day, block, counts, "ok", late["received"]))
    return out
