#!/usr/bin/env python3
"""Generate browser types and the embedded schema from the wire schema.

Runs on: developer laptop, CI. Standard library only; no network.
  scripts/gen_wire_types.py          rewrite web/src/generated/*
  scripts/gen_wire_types.py --check  exit 1 if the committed files are stale
"""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))

from eye.wire.validate import SCHEMA_PATH, WireSchema  # noqa: E402

OUT_DIR = ROOT / "web" / "src" / "generated"
HEADER = (
    "// GENERATED by scripts/gen_wire_types.py from schemas/eye-wire.v4.schema.json.\n"
    "// Do not edit by hand; run the generator and commit the result.\n"
)


def literal(value: object) -> str:
    return json.dumps(value)


def ts_type(node: dict, indent: str = "") -> str:
    if "$ref" in node:
        return node["$ref"].split("/")[-1]
    if "oneOf" in node:
        return " | ".join(ts_type(option, indent) for option in node["oneOf"])
    if "const" in node:
        return literal(node["const"])
    if "enum" in node:
        return " | ".join(literal(option) for option in node["enum"])
    names = node.get("type", "object")
    names = [names] if isinstance(names, str) else names
    parts = []
    for name in names:
        if name == "object":
            parts.append(object_type(node, indent))
        elif name == "array" and "prefixItems" in node:
            members = [ts_type(child, indent) for child in node["prefixItems"]]
            rest = node.get("items", False)
            if rest is not False:
                members.append(f"...({ts_type(rest, indent)})[]")
            parts.append(f"readonly [{', '.join(members)}]")
        elif name == "array":
            item = ts_type(node.get("items", {}), indent)
            parts.append(f"({item})[]" if " " in item else f"{item}[]")
        elif name in ("number", "integer"):
            parts.append("number")
        else:
            parts.append(name)  # string, boolean, null
    return " | ".join(parts)


def object_type(node: dict, indent: str) -> str:
    properties = node.get("properties", {})
    if not properties:
        return "Record<string, never>"
    required = set(node.get("required", []))
    inner = indent + "  "
    lines = ["{"]
    for name, child in properties.items():
        optional = "" if name in required else "?"
        doc = child.get("description")
        if doc:
            lines.append(f"{inner}/** {doc} */")
        lines.append(f"{inner}readonly {name}{optional}: {ts_type(child, inner)};")
    lines.append(f"{indent}}}")
    return "\n".join(lines)


def render_types(schema: dict) -> str:
    out = [HEADER]
    for name, node in schema["$defs"].items():
        doc = node.get("description")
        if doc:
            out.append(f"/** {doc} */")
        out.append(f"export type {name} = {ts_type(node)};\n")
    return "\n".join(out)


def render_schema(raw: bytes) -> str:
    digest = hashlib.sha256(raw).hexdigest()
    compact = json.dumps(json.loads(raw), separators=(",", ":"), sort_keys=True)
    return (
        HEADER
        + f'export const WIRE_SCHEMA_SHA256 = "{digest}";\n'
        + f"export const WIRE_SCHEMA_VERSION = {json.dumps(version(json.loads(raw)))};\n"
        + f"export const WIRE_SCHEMA_JSON = {json.dumps(compact)};\n"
    )


def version(schema: dict) -> str:
    """The one protocol version every message of this schema carries."""
    return schema["$defs"]["SchemaVersion"]["const"]


def outputs() -> dict[Path, str]:
    raw = SCHEMA_PATH.read_bytes()
    schema = json.loads(raw)
    WireSchema(schema)  # refuse unsupported keywords before generating anything
    return {
        OUT_DIR / "wire-types.ts": render_types(schema),
        OUT_DIR / "wire-schema.ts": render_schema(raw),
    }


def main(argv: list[str]) -> int:
    check = "--check" in argv[1:]
    stale = []
    for path, content in outputs().items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        if check:
            stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            print(f"wrote {path.relative_to(ROOT)}")
    if stale:
        print(f"gen_wire_types: STALE, regenerate: {', '.join(stale)}", file=sys.stderr)
        return 1
    if check:
        print("gen_wire_types: generated files are current")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
